# Generated by Django 6.0.4 on 2026-04-24 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="users",
            table="tbl_users",
        ),
    ]
