# Generated by Django 6.0.4 on 2026-04-24 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_alter_users_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="Products",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("price", models.IntegerField()),
            ],
            options={
                "db_table": "tbl_products",
            },
        ),
    ]
